language: python
required: sudo
dist: precise
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - sudo apt-get install python-tk
    - sudo apt-get install python3-tk
    - sudo apt-get install libtk-img
    - pip install codecov coverage nose
script:
    - python -m pip install .
    - python -m nose --with-coverage --cover-package=ttkthemes --cover-xml
after_success:
    - python -m codecov
